version: "3"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - ./app/logs:/app/logs


  db:
    image: mongo:latest
    container_name: database
    ports:
      - '27017:27017'
    volumes:
      - ./db/data:/data/db
      - ./db/logs:/var/log/mongodb
