version: "3"

services:
  app1:
      build: ./app
      tty: true
      volumes:
        - './app/logs:/app/logs'
  app2:
    build: ./app
    tty: true
    volumes:
      - './app/logs:/app/logs'
  app3:
    build: ./app
    tty: true
    volumes:
      - './app/logs:/app/logs'
  app4:
    build: ./app
    tty: true
    volumes:
      - './app/logs:/app/logs'
  app5:
    build: ./app
    tty: true
    volumes:
      - './app/logs:/app/logs'
  db:
    build: ./db
    volumes:
      - ./db/data:/data/db
      - ./db/logs:/var/log/mongodb
  nginx:
    build: ./nginx
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
