version: "3"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build:
      context: ./app
    volumes:
      - ./app/logs:/app/logs

  app2:
    build:
      context: ./app
    volumes:
      - ./app/logs:/app/logs

  app3:
    build:
      context: ./app
    volumes:
      - ./app/logs:/app/logs

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: matan
      MONGO_INITDB_ROOT_PASSWORD: matan
    volumes:
      - ./db/data:/data/db
      - ./db/logs:/var/log/mongodb
