version: "3"

services:
  app1:
    build: ./app
    tty: true
    volumes:
      - "./app/logs:/app/logs"
    depends_on:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=whist_cloud
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
